import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import '../models/contribute_result.dart';

class ContributeService {
  String buildNewContent(String? existingContent, DateTime now) {
    final timestamp = DateFormat('yyyy-MM-dd HH:mm').format(now);
    final newLine = '- $timestamp IST — keep the streak alive 🟩';

    if (existingContent == null || existingContent.isEmpty) {
      return '# Greener Log\n<!-- Auto-generated by GitHub Greener app -->\n\n$newLine\n';
    }

    return '$existingContent\n$newLine\n';
  }

  Future<ContributeResult> contribute({
    required String owner,
    required String repoName,
    required String pat,
  }) async {
    final filePath = '.greener/log.md';
    final url = 'https://api.github.com/repos/$owner/$repoName/contents/$filePath';
    final headers = {
      'Authorization': 'bearer $pat',
      'Content-Type': 'application/json',
      'User-Agent': 'GitHubGreener/1.0',
      'Accept': 'application/vnd.github+json',
    };

    try {
      // Step 1: GET existing file
      String? existingSha;
      String? existingContent;

      final getResponse = await http.get(Uri.parse(url), headers: headers);

      if (getResponse.statusCode == 200) {
        final data = jsonDecode(getResponse.body);
        existingSha = data['sha'];
        // decode base64 content
        existingContent = utf8.decode(
          base64Decode((data['content'] as String).replaceAll('\n', ''))
        );
      } else if (getResponse.statusCode != 404) {
        return ContributeResult(success: false, error: 'GET failed: ${getResponse.statusCode}');
      }

      // Step 2: Build new content
      final newContent = buildNewContent(existingContent, DateTime.now());
      final encoded = base64Encode(utf8.encode(newContent));

      // Step 3: PUT updated file
      final body = <String, dynamic>{
        'message': 'chore: update greener log [skip ci]',
        'content': encoded,
      };
      if (existingSha != null) body['sha'] = existingSha;

      final putResponse = await http.put(
        Uri.parse(url),
        headers: headers,
        body: jsonEncode(body),
      );

      if (putResponse.statusCode == 200 || putResponse.statusCode == 201) {
        final data = jsonDecode(putResponse.body);
        final commitUrl = data['commit']['html_url'] as String?;
        return ContributeResult(success: true, commitUrl: commitUrl);
      } else {
        return ContributeResult(success: false, error: '${putResponse.statusCode}');
      }
    } catch (e) {
      return ContributeResult(success: false, error: e.toString());
    }
  }
}
